### ISSUE TITLE
500 Error on Dashboard

### ISSUE THREAD

**Issue by mondele** [unfoldingWord-dev/gogs-custom#7]
When a user is a member of a deleted group (and possibly at other times) there is a 500 error when going to the Dashboard page.

**Comment by mondele** [comment]
Is there any hope of this being fixed?

**Comment by jag3773** [comment]
Issue moved to [unfoldingWord-dev/gogs #179](https://github.com/unfoldingWord-dev/gogs/issues/179) via [**ZenHub**](https://www.zenhub.com/)
